FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.5

RUN bin/elasticsearch-plugin install --batch analysis-ukrainian \
    && bin/elasticsearch-plugin install --batch analysis-kuromoji \
    && bin/elasticsearch-plugin install --batch analysis-smartcn