FROM docker.elastic.co/elasticsearch/elasticsearch:8.13.4

RUN bin/elasticsearch-plugin install --batch analysis-ukrainian \
    && bin/elasticsearch-plugin install --batch analysis-kuromoji \
    && bin/elasticsearch-plugin install --batch analysis-smartcn