apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "news-crawler.backend.configmapName" . }}
  labels:
    {{- include "news-crawler.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  APP_MODE: {{ .Values.backend.config.appMode | quote }}
  CORS_ORIGINS: {{ .Values.backend.config.corsOrigins | quote }}
  DEFAULT_KEYWORDS: {{ .Values.backend.config.defaultKeywords | quote }}
  ELASTICSEARCH_URL: {{ include "news-crawler.elasticsearch.url" . | quote }}