{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "news-crawler.elasticsearch.fullname" . }}
  labels:
    {{- include "news-crawler.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  type: ClusterIP
  selector:
    {{- include "news-crawler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  ports:
    - name: http
      port: {{ .Values.elasticsearch.service.port }}
      targetPort: http
{{- end }}