{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "news-crawler.postgres.fullname" . }}
  labels:
    {{- include "news-crawler.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "news-crawler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
{{- end }}