"""Create Robots model

Revision ID: 20260508_AddRobotsModel
Revises: 20260421_KeywordHitArticleFk
Create Date: 2026-05-08 00:31:45.266303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260508_AddRobotsModel'
down_revision: Union[str, None] = '20260421_KeywordHitArticleFk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('robots_content', sa.Text(), nullable=True),
    sa.Column('crawl_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robots')
    # ### end Alembic commands ###
