"""20260809_Add_Normalized_Fierlds

Revision ID: 20260908_AddNormFd
Revises: 20260902_AddPermScope
Create Date: 2026-09-08 17:08:44.323255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260908_AddNormFd'
down_revision: Union[str, None] = '20260902_AddPermScope'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('normilized_text', sa.Text(), nullable=False))
    op.add_column('articles', sa.Column('normalized_text_lower', sa.Text(), nullable=False))
    op.add_column('articles', sa.Column('urls', sa.JSON(), nullable=True))
    op.add_column('articles', sa.Column('hashtags', sa.JSON(), nullable=True))
    op.add_column('articles', sa.Column('mentions', sa.JSON(), nullable=True))
    op.add_column('articles', sa.Column('normalization_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'normalization_version')
    op.drop_column('articles', 'mentions')
    op.drop_column('articles', 'hashtags')
    op.drop_column('articles', 'urls')
    op.drop_column('articles', 'normalized_text_lower')
    op.drop_column('articles', 'normilized_text')
    # ### end Alembic commands ###
