"""Alter Owner column to be not null

Revision ID: 20260729_AlterOwnerColumntNotNull
Revises: 20260729_OwnerIdBackfill
Create Date: 2026-07-29 00:33:56.825497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260729_AlterOwnerNotNull'
down_revision: Union[str, None] = '20260729_OwnerIdBackfill'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('crawl_jobs', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('keyword_hits', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('monitored_keywords', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('outbox_events', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sources', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('outbox_events', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('monitored_keywords', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('keyword_hits', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('crawl_jobs', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('articles', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
