"""Added Issued Refresh toen model

Revision ID: 20260804_AddedIssuedRefreshToken
Revises: 20260729_AlterOwnerNotNull
Create Date: 2026-08-04 00:36:16.539542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260804_AddedIssuedRefreshToken'
down_revision: Union[str, None] = '20260729_AlterOwnerNotNull'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_refresh_token',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_issued_refresh_token_user_id'), 'issued_refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issued_refresh_token_user_id'), table_name='issued_refresh_token')
    op.drop_table('issued_refresh_token')
    # ### end Alembic commands ###
