"""Add property next_run_at to Source

Revision ID: 20260605_NextRunAt
Revises: 20260525_AddLastMsgId
Create Date: 2026-06-05 23:41:21.904869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260605_NextRunAt'
down_revision: Union[str, None] = '20260525_AddLastMsgId'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_sources_next_run_at'), 'sources', ['next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_next_run_at'), table_name='sources')
    op.drop_column('sources', 'next_run_at')
    # ### end Alembic commands ###
