"""Add Auth models

Revision ID: 20260728_AuthModels
Revises: 20260702_OutboxEvents
Create Date: 2026-07-28 22:47:18.424119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260728_DeleteIndex'
down_revision: Union[str, None] = '20260702_OutboxEvents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_pending_due', table_name='outbox_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_outbox_events_pending_due', 'outbox_events', ['status', 'next_attempt_at'], unique=False)
    # ### end Alembic commands ###
