"""remove unique constrain from Monitored Ketword, we need this for the user

Revision ID: 20260901_RemoveMonitoredKeywordUnique
Revises: 20260817_AuthAuditTimestamps
Create Date: 2026-09-01 17:06:29.536016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260901_RemoMonitKeywordUnique'
down_revision: Union[str, None] = '20260817_AuthAuditTimestamps'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'issued_refresh_token', ['jti'])
    op.drop_constraint('monitored_keywords_keyword_key', 'monitored_keywords', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('monitored_keywords_keyword_key', 'monitored_keywords', ['keyword'])
    op.drop_constraint(None, 'issued_refresh_token', type_='unique')
    # ### end Alembic commands ###
