"""Add Owner property

Revision ID: 20260729_OwnerIdBackfill
Revises: 20260728_AuthModels
Create Date: 2026-07-29 00:27:14.002771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260729_OwnerIdBackfill'
down_revision: Union[str, None] = '20260728_AuthModels'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLES = [
    "sources",
    "crawl_jobs",
    "monitored_keywords",
    "outbox_events",
    "articles",
    "keyword_hits",
]

def _fk_name(table: str) -> str:
    return f"fk_{table}_owner_id_users"

def upgrade() -> None:
    bind = op.get_bind()

    # 1. Add owner_id (nullable) + FK to every table.
    for table in _TABLES:
        op.add_column(table, sa.Column("owner_id", sa.Uuid(), nullable=True))
        op.create_foreign_key(
            _fk_name(table),
            table,
            "users",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # 2. Resolve the system admin user id once.
    admin_id = bind.execute(
        sa.text("SELECT id FROM users WHERE username = :username"),
        {"username": "admin"},
    ).scalar_one_or_none()

    if admin_id is None:
        raise RuntimeError(
            "Cannot backfill owner_id: no 'admin' user found. "
            "Run app.db.seed_data.seed_data() (or seed manually) before "
            "applying this migration."
        )

    # 3. Backfill every table to the system admin.
    for table in _TABLES:
        bind.execute(
            sa.text(f"UPDATE {table} SET owner_id = :admin_id WHERE owner_id IS NULL"),
            {"admin_id": admin_id},
        )

    # 4. Tighten constraints here once backfill is verified, e.g.:
    # for table in _TABLES:
    #     op.alter_column(table, "owner_id", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in _TABLES:
        op.drop_constraint(_fk_name(table), table, type_="foreignkey")
        op.drop_column(table, "owner_id")
    # ### end Alembic commands ###
